# Generated by Django 4.2 on 2023-07-25 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('created', models.DateTimeField(auto_created=True)),
                ('timesheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours_worked', models.FloatField(default=0.0)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('created', models.DateTimeField(auto_created=True)),
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('monthly_salary', models.FloatField(default=0.0)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
